"""re

Revision ID: 456941115be1
Revises: 206a8edfaaed
Create Date: 2018-01-24 15:10:49.044476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '456941115be1'
down_revision = '206a8edfaaed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
